### PR TITLE
Added error handling in commands and speed request

### PR DESCRIPTION
**Pull request by bstoney**
I have tested this with my S22i and checked the metrics reporting is still working. There are still some disconnects in the UDP service, but it is reconnecting and handled messages correctly. Changing the speed is not yet working and I need to check the swipe coordinates.

Now seeing speed requests handled in the log

```
10-29 19:00:08.923  6471 10070 I UDPListenerService: Got UDB broadcast from 192.168.0.5, message: 10;
10-29 19:00:08.923  6471 10070 D UDPListenerService: 10;
10-29 19:00:08.923  6471 10070 D UDPListenerService: requestSpeed: 10.0
10-29 19:00:08.945  6471 10070 D UDPListenerService: input swipe 1845 930 1845 1019 200
10-29 19:00:08.949  6471 10070 I UDPListenerService: Waiting for UDP broadcast
```

### CODE REVIEW

**Comment by cagnulein** [comment]
wow that's awesome!
about the coordinate: they are about the tablet of @victorypoint so it could be different on yours

@victorypoint could you please try this PR? do you need the apk or you can build it on your own?

**Comment by victorypoint** [comment]
@cagnulein, yes, I would need an APK to test

**Comment by cagnulein** [comment]
ok @victorypoint i'm merging this, so you will find the new apk in the actions tab on github. Let me know

**Comment by victorypoint** [comment]
Github discussion re: Nordictrack auto speed & incline starts July 4 2022 - https://github.com/cagnulein/qdomyos-zwift/issues/815#issuecomment-1174032533

**Comment by cagnulein** [comment]
@bstoney @victorypoint tried and had the same results of my last build (check the full report on the link above). could you please check it?
thanks

**Pull request merged**
