### PR TITLE
New Log file from the new ifit version

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
@victorypoint new apk with the log that you found https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11202265658/artifacts/2020740205

what I did:
- since that log is probably only available on adb, i used the adb service inside the companion to put the tail in a tmp file in /tmp/qz.log So you should see this file
- also qz is getting the log from it and using the new format sending it to the qz main app

Of course I wasn't able to test anything, so let me know with a log if something works 

Thanks as always!

**Comment by cagnulein** [comment]
Yes we can, but usually it's not possible due to android privacy crap :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 6 ott 2024 alle 16:18 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, ok good start. It looks like there's adb connection errors and no /tmp/qz.log was found. Is qz.log supposed to be on /sdcard or device folder? I can't find it. Logcat attached.
[stream-logcat.txt](https://github.com/user-attachments/files/17270819/stream-logcat.txt)

**Comment by cagnulein** [comment]
/tmp/ should be in ram
anyway the issue is the adb connection
i will investigate this tomorrow, i already have this algorithm inside the
companion because i was already using it for some kind of devices, so it
could be a stupid issue

i will let you know
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 6 ott 2024 alle 22:16 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i tried to access directly to the file, let me know

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11210861609/artifacts/2022509666

**Comment by victorypoint** [comment]
@cagnulein, with new apk I see a parsing line in logcat but no metrics are logged after that. I checked the new wolflog and all speed/incline changes were recorded.
`QZ:Service: Parsing /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt`
[stream-logcat.txt](https://github.com/user-attachments/files/17279684/stream-logcat.txt)

**Comment by cagnulein** [comment]
wow that's great! so you were right, we can read it!
Let me fix the parsing

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle ore 16:00 Al Udell ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
it was a rookie mistake
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11217455297/artifacts/2024283835

let me know!

**Comment by victorypoint** [comment]
@cagnulein, using adbremoteshell APK I confirmed that log is also readable by local ADB.
PXL_20241007_142700055

**Comment by cagnulein** [comment]
perfect, try this 
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11217455297/artifacts/2024283835

**Comment by victorypoint** [comment]
@cagnulein, bingo! We have parsing in the log. Ready for next steps.
[stream-logcat.txt](https://github.com/user-attachments/files/17280315/stream-logcat.txt)

**Comment by cagnulein** [comment]
Amazing! The current QZ version should be already ready to read these, i already made the changes in order to be retrocompatible!
Let me know!

**Comment by victorypoint** [comment]
@cagnulein, ok I didn't see udp messages in logcat nor any metrics via dircon in QZ.

**Comment by cagnulein** [comment]
mmm I guess I fixed now https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11218139491/artifacts/2024482219

**Comment by victorypoint** [comment]
@cagnulein, wow! You nailied it. Every speed and incline change picked up by QZ perfectly. Nice work as always!
[stream-logcat.txt](https://github.com/user-attachments/files/17281351/stream-logcat.txt)

**Comment by cagnulein** [comment]
You did the hardest part :) ok I will add a fallback in case of missing
file so the companion  will be retro compatible

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 18:01 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein thanks! So this ifit beta appears to be rolled out as ifit2 but seems to be a bit of a moving target as they keep adding more features and making changes. Maybe keep the OCR development going as the might disable the log or tighten up more features. We're so close with ai.server and paddleocr.

**Comment by cagnulein** [comment]
Sounds like a plan!

**Comment by victorypoint** [comment]
@cagnulein, I forgot to mention, when qz.companion launches on treadmill boot, it remains onscreen and covers up the iFit2 login screen. We didn't have this problem with previous iFit as it would launch after. iFit2 is now composed of several separate apps. The launcher is named com.ifit.gandalf. Is there a way to have qz.companion launch before or hide it to the background?

**Comment by cagnulein** [comment]
Sure I can force to hide itself. Are you able somehow to show it again in
case? I'm wondering if, in the first time setup, I have to avoid to hide it
in order to give the possibility to the user to set it up

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 20:44 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, yes I'm able to switch to the companion via Android task tray. On old iFit install script we forced treadmill to reboot after install so ADB incline control would work. With iFit2, since we don't have ADB control yet, we can avoid treadmill reboot so that companion can stay onscreen for setup.

**Comment by cagnulein** [comment]
hah adb swipes doesn't work?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 21:01 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, yeah it's frustrating. They changed the onscreen controls to columns of single buttons. No slider for fractional values anymore. More frustrating is not all buttons fit on a single screen so you have to swipe to get to higher/lower buttons. Arughh!

**Comment by cagnulein** [comment]
hah right now i remember. let's see if they will change their mind :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 21:06 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@victorypoint https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11231015076/artifacts/2027987754

i added the retrcompatibility with the old ifit version and i added the hide event at the startup of the app

let me know, in case i will merge it
thanks

**Comment by victorypoint** [comment]
@cagnulein, new apk works perfect for hiding the companion. Companion also works fine with privileged mode disabled (which is fine since we're not doing adb control).

**Comment by cagnulein** [comment]
amazing! let's merge this so!

**Comment by victorypoint** [comment]
@cagnulein, I just discovered a minor bug. While doing a manual workout run with new apk and ifit2, once in a while my speed would jump to 0 for a few seconds then rebound back to where it was. I'll have to dig into this more when I have time but I suspect Companion is reading the wolflog file perhaps when it is locked or busy, thus returning a 0 speed? I checked the wolflog after my run and it shows no speed drops to 0. Anyways, I'll try to get this sorted.

**Comment by cagnulein** [comment]
if you can get a adb logcat with the issue i can fix it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 21:14 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, i was able to recreate the problem quite easily (it happens on every run actually). So I gathered all the logs. I don't see anything unusual in the wolflog or logcat, but the QZ log appears to capture the speed drops, for example:

```
Line 38121: Tue Oct 8 19:00:43 2024 1728424843808 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "Current Speed: 8.04"
Line 38131: Tue Oct 8 19:00:43 2024 1728424843855 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "Current Speed: 8.04"
Line 38138: Tue Oct 8 19:00:43 2024 1728424843880 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "Current Speed: 0"
Line 38144: Tue Oct 8 19:00:43 2024 1728424843952 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "Current Speed: 8.04"
Line 38149: Tue Oct 8 19:00:44 2024 1728424844023 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "Current Speed: 8.04"
```

[_stall.zip](https://github.com/user-attachments/files/17299792/_stall.zip)

**Comment by cagnulein** [comment]
fixed in the 3.5.1 available here on github @victorypoint ! the problem was that the windows pc version of qz was reading also the adb logcat and qz companion was logging the entire line with the new format, so qz on pc was going mad :) now i'm not logging it anymore and so it should be fine. Let me know!

**Comment by victorypoint** [comment]
@cagnulein, ok cool. I see the nightly build of QZ windows but not 3.5.1?
https://github.com/cagnulein/qdomyos-zwift/releases

**Comment by cagnulein** [comment]
@victorypoint here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.5.1/QZCompanionNordictrackTreadmill.apk

**Comment by cagnulein** [comment]
don't change the qz app on the pc for the moment

**Comment by victorypoint** [comment]
@cagnulein, ok I'll wait.

**Comment by cagnulein** [comment]
yeah i mean try just using the 3.5.1 of the companion, you haven't to change the qz pc part :)

**Comment by cagnulein** [comment]
the problem was only on the companion

**Comment by victorypoint** [comment]
@cagnulein, got it. Okay so the 3.5.1 companion seems to fix the speed drops. Great job! Currently using 2.16.30 of QZ on Windows.

**Comment by cagnulein** [comment]
glad to hear it!

**Comment by jones-d** [comment]
@cagnulein - is this fix available in the iOS version? Back from injury and trying to get the connection back with the new beta UI. Also my iOS beta has expired.

**Comment by cagnulein** [comment]
This is about the companion, it's not involving the app on the phone

I already sent the update to the beta on ios, anyway there aren't changes for this in the ios Beta.

You can download the apk of this as usual in the release of the companion page

**Comment by jones-d** [comment]
Thanks, did a full bike reset and using new iFIT UI, installed via companion app via adb, have 2.17.0 iOS app. I can see speed, but no cadance or watts. Is this the same error as open at the moment?

**Comment by cagnulein** [comment]
Can you share a debug log so I can check it
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 19:12 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
IOS app
[debug-Sun_Dec_1_18_23_59_2024.log](https://github.com/user-attachments/files/17969942/debug-Sun_Dec_1_18_23_59_2024.log)

**Comment by jones-d** [comment]
adb-debug
[Archive.zip](https://github.com/user-attachments/files/17969948/Archive.zip)

**Comment by cagnulein** [comment]
Thanks, I'll check it out.


Il giorno dom 1 dic 2024 alle 19:31 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
Also, now the companion app is installed, I think it is doing swipe commands, as the UI changes on it’s own making the bike unusable. 

https://github.com/user-attachments/assets/f17a8519-411f-4813-ac48-4119f9313be5

**Comment by cagnulein** [comment]
This could be a good sign since we would be able to have also auto
resistance

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 19:57 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
Agree, but anyway to detect if we are in manual mode? As it is very difficult to navigate around the iFIT screen?On 1 Dec 2024, at 18:59, Roberto Viola ***@***.***> wrote:﻿
This could be a good sign since we would be able to have also auto

resistance



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 1 dic 2024 alle 19:57 jones-d ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Simply turn off qz, it should stop. I will check the log in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 21:10 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
How do you turn off?On 1 Dec 2024, at 20:14, Roberto Viola ***@***.***> wrote:﻿
Simply turn off qz, it should stop. I will check the log in the next days



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 1 dic 2024 alle 21:10 jones-d ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
The app on the phone. Close it. If the companion doesn't receive any input from the phone it can't do any action, at least it shouldn't

**Comment by cagnulein** [comment]
@jones-d are you able to collect also the /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt

because it seems it doesn't log the other metrics. if so you need to use this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11027669224/artifacts/1975357631

**Comment by jones-d** [comment]
@cagnulein Installed the new apk, confirmed screen access.  Did simple test, QZ App on iOS, no speed, cadance or watts.
[log.latest.txt](https://github.com/user-attachments/files/17979772/log.latest.txt)

**Comment by cagnulein** [comment]
ok so ifit doesn't log anything else out from speed or pulse unfortunately. so OCR is the way to go.
From this new APK can you show me a logcat so I will understand if the OCR engine is working?
Thanks

**Comment by jones-d** [comment]
[logcat.txt](https://github.com/user-attachments/files/17994010/logcat.txt)
Here is the logcat file from the same time.

**Comment by cagnulein** [comment]
i guess i got it, could you try this new apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/12142442404/artifacts/2268026122

Thanks

**Comment by jones-d** [comment]
Thanks, @cagnulein! I installed it and did a very quick test. Good progression, watts and resistance are now being received, but no cadence or speed.
[debug-Tue_Dec_3_18_59_27_2024.log](https://github.com/user-attachments/files/17997685/debug-Tue_Dec_3_18_59_27_2024.log)
[log.latest.txt](https://github.com/user-attachments/files/17997687/log.latest.txt)
[logcat.txt](https://github.com/user-attachments/files/17997688/logcat.txt)
[2024-12-03.logs.txt](https://github.com/user-attachments/files/17997691/2024-12-03.logs.txt)

**Comment by cagnulein** [comment]
@jones-d i checked the log and i see over and over these messages

```
12-03 18:58:38.062  1857  1857 D OCRlines: 1 Nice job!
12-03 18:58:38.062  1857  1857 D OCRlines: 2 Keep up the great work
12-03 18:58:38.062  1857  1857 D OCRlines: 3 My Manual Workout
12-03 18:58:38.062  1857  1857 D OCRlines: 4 O2 min
12-03 18:58:38.062  1857  1857 D OCRlines: 5 1%
12-03 18:58:38.062  1857  1857 D OCRlines: 6 0 %
12-03 18:58:38.062  1857  1857 D OCRlines: 7 -1%
12-03 18:58:38.063  1857  1857 D OCRlines: 8 2017 km 5 cals (est)
12-03 18:58:38.063  1857  1857 D OCRlines: 9 Incline 0.0 % avg 0.0 % max
12-03 18:58:38.063  1857  1857 D OCRlines: 10 A0m
12-03 18:58:38.063  1857  1857 D OCRlines: 11 23 avg rpm
12-03 18:58:38.063  1857  1857 D OCRlines: 12 Resistance 2 avg. 4 max
12-03 18:58:38.063  1857  1857 D OCRlines: 13 # Apps
12-03 18:58:38.063  1857  1857 D OCRlines: 14 42 avg watts
12-03 18:58:38.064  1857  1857 D OCRlines: 15 *3 Quick start
```

where you on the manual workout window on ifit running a manual workout? it doesn't seem so

let me know

**Comment by jones-d** [comment]
Thank you! I now have access to privileged mode when the bike boots up, and it starts with the standard Android tablet interface. I need to manually open the iFit app each time. After launching the app, I did a manual workout using the oval track displayed on the screen. While the QZ app is open, I notice that screen swipes occasionally trigger the opening and closing of various standard Android windows. It’s possible that I’m launching the incorrect iFit window, which may be causing it to lose focus.Is it worth disabling the screen interactions at this stage?On 4 Dec 2024, at 08:15, Roberto Viola ***@***.***> wrote:﻿
@jones-d i checked the log and i see over and over these messages
12-03 18:58:38.062  1857  1857 D OCRlines: 1 Nice job!
12-03 18:58:38.062  1857  1857 D OCRlines: 2 Keep up the great work
12-03 18:58:38.062  1857  1857 D OCRlines: 3 My Manual Workout
12-03 18:58:38.062  1857  1857 D OCRlines: 4 O2 min
12-03 18:58:38.062  1857  1857 D OCRlines: 5 1%
12-03 18:58:38.062  1857  1857 D OCRlines: 6 0 %
12-03 18:58:38.062  1857  1857 D OCRlines: 7 -1%
12-03 18:58:38.063  1857  1857 D OCRlines: 8 2017 km 5 cals (est)
12-03 18:58:38.063  1857  1857 D OCRlines: 9 Incline 0.0 % avg 0.0 % max
12-03 18:58:38.063  1857  1857 D OCRlines: 10 A0m
12-03 18:58:38.063  1857  1857 D OCRlines: 11 23 avg rpm
12-03 18:58:38.063  1857  1857 D OCRlines: 12 Resistance 2 avg. 4 max
12-03 18:58:38.063  1857  1857 D OCRlines: 13 # Apps
12-03 18:58:38.063  1857  1857 D OCRlines: 14 42 avg watts
12-03 18:58:38.064  1857  1857 D OCRlines: 15 *3 Quick start

where you on the manual workout window on ifit running a manual workout? it doesn't seem so
let me know

**Comment by cagnulein** [comment]
i tried to add some new log in this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/12155996067/artifacts/2272087177
let me know

**Comment by jones-d** [comment]
Updated to new apk, ran a short test, nothing in the QZ app
[2024-12-04.logs.txt](https://github.com/user-attachments/files/18013631/2024-12-04.logs.txt)
[debug-Wed_Dec_4_19_54_44_2024.log](https://github.com/user-attachments/files/18013632/debug-Wed_Dec_4_19_54_44_2024.log)
[log.latest.txt](https://github.com/user-attachments/files/18013633/log.latest.txt)
[logcat.txt](https://github.com/user-attachments/files/18013634/logcat.txt)

**Comment by cagnulein** [comment]
@jones-d does it ask to record the screen and you said yes because i don't see the OCR engine running here at all

**Comment by jones-d** [comment]
Yes, it did, and I approved. On 5 Dec 2024, at 09:27, Roberto Viola ***@***.***> wrote:﻿
@jones-d did it ask to record the screen and you said yes because i don't see the OCR engine running here at all

**Comment by jones-d** [comment]
OK—I reinstalled and reset the permission to view the screen. When I retested, I could see the OCR in the log file. However, I did notice a widget on the screen in the first test, so I reran with the widget removed.
[debug-Thu_Dec_5_17_11_40_2024.log](https://github.com/user-attachments/files/18027173/debug-Thu_Dec_5_17_11_40_2024.log)
[log.latest.txt](https://github.com/user-attachments/files/18027174/log.latest.txt)
[2024-12-05.logs.txt](https://github.com/user-attachments/files/18027175/2024-12-05.logs.txt)
[logcat.txt](https://github.com/user-attachments/files/18027176/logcat.txt)

**Comment by cagnulein** [comment]
Ok perfect i can see now the metrics in the companion logs
I will be out a couple of days, I will send you another one with,
hopefully, final fix
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 dic 2024 alle 18:16 jones-d ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @jones-d log checked
i added also the cadence to the info sent in this new apk 

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/12232366169/artifacts/2292599782

also if you enable the speed based on power setting under the bike options in qz, you should have all the metrics now

let me know!

**Comment by jones-d** [comment]
Thanks, I installed it (I needed to do it twice as the first time I didn't see any data in QZ) - Now I can see all but cadence

[2024-12-09.logs.txt](https://github.com/user-attachments/files/18059627/2024-12-09.logs.txt)
[debug-Mon_Dec_9_09_58_03_2024.log](https://github.com/user-attachments/files/18059629/debug-Mon_Dec_9_09_58_03_2024.log)
[log.latest.txt](https://github.com/user-attachments/files/18059630/log.latest.txt)
[logcat.txt](https://github.com/user-attachments/files/18059631/logcat.txt)

**Comment by cagnulein** [comment]
got it, try this fix https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/12234010397/artifacts/2293058251

**Comment by jones-d** [comment]
Thank you - a quick test appears to work; I will conduct further testing and let you know.

**Comment by cagnulein** [comment]
Cool, let me know.


Il giorno lun 9 dic 2024 alle 18:40 jones-d ***@***.***> ha
scritto:

> Thank you - a quick test appears to work; I will conduct further testing
> and let you know.
>

**Pull request merged**
