### PR TITLE
Sign APK

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
@IzzySoft could you please check if this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/7247410089/artifacts/1121176980 satisfies the fdroid needs?

@victorypoint could you just check if this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/7247410089/artifacts/1121176980 still works? i just signed it to fix the #61 

let me know guys
then I will merge this

**Comment by IzzySoft** [comment]
```
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework, Apache-2.0
* AndroidX Activity (/androidx/activity): Utility, Apache-2.0
* Android Jetpack Annotations (/androidx/annotation): Utility, Apache-2.0
* Arch (/androidx/arch): Utility, Apache-2.0
* AppCompat (/androidx/appcompat): Utility, Apache-2.0
* Cardview (/androidx/cardview): UI Component, Apache-2.0
* Android Support Library collections (/androidx/collection): Utility, Apache-2.0
* Concurrent (/androidx/concurrent): Utility, Apache-2.0
* Constraint Layout Library (/androidx/constraintlayout): Utility, Apache-2.0
* Coordinatorlayout (/androidx/coordinatorlayout): UI Component, Apache-2.0
* Androidx Core (/androidx/core): Utility, Apache-2.0
* AndroidX Cursor Adapter (/androidx/cursoradapter): Utility, Apache-2.0
* Android Support Library Custom View (/androidx/customview): UI Component, Apache-2.0
* Documentfile (/androidx/documentfile): UI Component, Apache-2.0
* Drawerlayout (/androidx/drawerlayout): UI Component, Apache-2.0
* Dynamicanimation (/androidx/dynamicanimation): UI Component, Apache-2.0
* AndroidX Fragment (/androidx/fragment): UI Component, Apache-2.0
* Interpolator (/androidx/interpolator): UI Component, Apache-2.0
* androidx.legacy (/androidx/legacy): Utility, Apache-2.0
* Lifecycle (/androidx/lifecycle): Utility, Apache-2.0
* Loader (/androidx/loader): Utility, Apache-2.0
* AndroidX Local Broadcast Manager (/androidx/localbroadcastmanager): Utility, Apache-2.0
* Print (/androidx/print): Utility, Apache-2.0
* Recyclerview (/androidx/recyclerview): Utility, Apache-2.0
* Android Activity Saved State (/androidx/savedstate): Utility, Apache-2.0
* Tracing (/androidx/tracing): Utility, Apache-2.0
* Transition (/androidx/transition): UI Component, Apache-2.0
* Vectordrawable (/androidx/vectordrawable): UI Component, Apache-2.0
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility, Apache-2.0
* Viewpager (/androidx/viewpager): UI Component, Apache-2.0
* AndroidX Widget ViewPager2 (/androidx/viewpager2): UI Component, Apache-2.0
* AdbLib (/com/cgutman/adblib): Utility, BSD-3-Clause
* RemoteAdbShell (/com/cgutman/androidremotedebugger): Utility, Apache-2.0
* Google Material Design (/com/google/android/material): Utility, Apache-2.0
* Google Core Libraries for Java 6+ (/com/google/common): Utility, Apache-2.0
* Kotlin (/kotlin): Utility, Apache-2.0
* kotlinx.coroutines (/kotlinx/coroutines): Utility, Apache-2.0
* IntelliJ IDEA (/org/intellij): Utility, Apache-2.0

No offending libs found.
```

But it's a debug build, signed with a debug key. It should be signed by a release key if it shall go to my repo.

**Comment by cagnulein** [comment]
@IzzySoft my bad, try this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/7250732117/artifacts/1121843791

**Comment by cagnulein** [comment]
ok let's wait the confirmation from @victorypoint before merging it, even if i guess it will be ok

**Comment by victorypoint** [comment]
@cagnulein, okay I just gave this a good test and it works rock solid on my C2950. All auto-incline and workout features work fine.

**Comment by cagnulein** [comment]
thanks! i'm pushing into master so!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle ore 20:25 Al Udell ***@***.***>
ha scritto:

**Comment by IzzySoft** [comment]
Yay! Please let me know when the first release with the new signature goes live. I need to take proper actions then on my end, too, so my repo accepts it. And congrats!

**Comment by cagnulein** [comment]
I already did, check this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.3.22

Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 22:47 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
* updated `AllowedSigningKeys` to the release key √
* re-enabled auto-updates √
* fetched latest release √
* triggered new index to be build, to confirm all is in place … Ooof. Huh? Oh.
* fixed `AllowedSigningKeys` to point to the Certificate (and not the public key) :see_no_evil: √
* triggered new index to be build again, to confirm all is in place √
* checking… Ah, we can remove the AntiFeature now – it's no longer a debug build :partying_face: 
* triggered new index to be build yet another time, to confirm all is in place √

All set then, thanks!

Last question: would there be some screenshots, or at least an icon (not the green Andy)? It looks a bit "naked" without:

image

**Comment by cagnulein** [comment]
Do you need the icon in the apk or even here?

**Comment by IzzySoft** [comment]
Ideally in Fastlane structure, see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688). If that's asked too much, you can provide them here – and if you want I return them in Fastlane format via PR so you can adjust them whenever needed. Including app short- and full descriptions.

**Comment by cagnulein** [comment]
Ok I can do it but not right now :) Is it a problem for now leaving in this way? Other than the fact that it's ugly?

**Comment by IzzySoft** [comment]
> Other than the fact that it's ugly?

Consider it a "cosmetical issue" then :rofl: And my offer stands. If you provide me any of those graphics, I can add them here ASAP – and when you feel ready to accept it, ship things back in Fastlane structures via a PR.

**Comment by cagnulein** [comment]
ok thanks, i will try to do my best!

**Pull request merged**
